name: Auto Merge Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check for mergeability
        id: check_mergeable
        run: |
          if [[ "${{ github.event.pull_request.mergeable }}" == "true" ]]; then
            echo "This pull request is mergeable."
            echo "::set-output name=mergeable::true"
          else
            echo "This pull request is not mergeable."
            echo "::set-output name=mergeable::false"
          fi

      - name: Automerge
        if: steps.check_mergeable.outputs.mergeable == 'true' && github.event.pull_request.user.login == 'exercism-solutions-syncer'
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: 'merge'  # Choose 'merge', 'squash', or 'rebase'
